#ifndef FIRO_QT_AUTOMINT_H
#define FIRO_QT_AUTOMINT_H

#include "walletmodel.h"

#include <QDialog>
#include <QPainter>
#include <QPaintEvent>

/**
 * Forward declaration of the Qt UI class for the AutoMint dialog.
 *
 * This class is generated by Qt's User Interface Compiler (uic) from the
 * AutoMintDialog UI form and provides the widgets and layout used by
 * AutoMintSparkDialog.
 */
namespace Ui {
    class AutoMintDialog;
}

enum class AutoMintSparkMode : uint8_t {
    MintAll, // come from overview page
    AutoMintAll // come from notification
};

class AutoMintSparkDialog : public QDialog
{
    Q_OBJECT;

public:
    explicit AutoMintSparkDialog(AutoMintSparkMode mode, QWidget *parent = 0);
    ~AutoMintSparkDialog();

public:
    int exec() override;
    void setModel(WalletModel *model);

    void paintEvent(QPaintEvent *event) Q_DECL_OVERRIDE;

private Q_SLOTS:
    void accept() override;
    void reject() override;

private:
    enum class AutoMintSparkProgress : uint8_t {
        Start,
        Unlocking,
        Minting
    };

    Ui::AutoMintDialog *ui;
    WalletModel *model;
    SparkModel *sparkModel;
    bool requiredPassphase;
    AutoMintSparkProgress progress;
    AutoMintSparkMode mode;

    void ensureSparkModel();
};

#endif // FIRO_QT_AUTOMINT_H