name: build Dockerfile

on:
  push:
    paths:
      - 'Dockerfile'
      - 'depends/**'
      - '.github/workflows/test-dockerfile.yml'
  pull_request:
    paths:
      - 'Dockerfile'
      - 'depends/**'
      - '.github/workflows/test-dockerfile.yml'

jobs:
  build:
    name: Build Dockerfile (${{ matrix.platform }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker buildx build --platform ${{ matrix.platform }} -t firo .
